

CREATE TABLE TipoSoggettoNIS (
    id          NUMBER(5) PRIMARY KEY,
    codice      VARCHAR2(20) NOT NULL UNIQUE
                CHECK (codice IN ('ESSENZIALE', 'IMPORTANTE')),
    descrizione VARCHAR2(255)
);
 

CREATE TABLE RegistroTabelle (
    id           NUMBER(5) PRIMARY KEY,
    nome_tabella VARCHAR2(100) NOT NULL UNIQUE
);


CREATE TABLE LogEstrazione (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_tabella_id NUMBER(5) NOT NULL REFERENCES RegistroTabelle(id),
    record_id           NUMBER(19) NOT NULL,          -- riferimento debole, non FK
    utente              VARCHAR2(100) NOT NULL,
    data_ora            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    tipo_operazione     VARCHAR2(30) NOT NULL
                        CHECK (tipo_operazione IN
                            ('INSERIMENTO', 'MODIFICA', 'ESTRAZIONE_CSV', 'CONSULTAZIONE')),
    snapshot_dati       CLOB                     -- opzionale, copia dei dati al momento del log
);
 
CREATE INDEX idx_logestrazione_tabella_record
    ON LogEstrazione (registro_tabella_id, record_id);
CREATE INDEX idx_logestrazione_data
    ON LogEstrazione (data_ora);


CREATE TABLE SoggettoNIS (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice_fiscale      VARCHAR2(16) NOT NULL UNIQUE,
    denominazione       VARCHAR2(255) NOT NULL,
    indirizzo_sede_legale VARCHAR2(255) NOT NULL,
    pec                 VARCHAR2(255) NOT NULL,
    email_funzionale    VARCHAR2(255),
    telefono            VARCHAR2(30),
    fatturato           NUMERIC(15,2),          -- nullable: PA esente (vedi campi_dati.md §2)
    bilancio            NUMERIC(15,2),           -- nullable: PA esente
    n_dipendenti        NUMBER(10),
    tipo_soggetto_id    NUMBER(5) NOT NULL REFERENCES TipoSoggettoNIS(id),
    data_creazione      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
 
CREATE INDEX idx_soggettonis_tipo ON SoggettoNIS (tipo_soggetto_id);
  

CREATE TABLE SoggettoNISStorico (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soggetto_nis_id         NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    versione                NUMBER(10) NOT NULL,
    denominazione           VARCHAR2(255) NOT NULL,
    indirizzo_sede_legale   VARCHAR2(255) NOT NULL,
    pec                     VARCHAR2(255) NOT NULL,
    email_funzionale        VARCHAR2(255),
    telefono                VARCHAR2(30),
    fatturato               NUMERIC(15,2),
    bilancio                NUMERIC(15,2),
    n_dipendenti            NUMBER(10),
    tipo_soggetto_id        NUMBER(5) NOT NULL REFERENCES TipoSoggettoNIS(id),
    valido_da               TIMESTAMP NOT NULL,
    valido_a                TIMESTAMP,           -- NULL se è la versione più recente
    log_estrazione_id       NUMBER(19) NOT NULL REFERENCES LogEstrazione(id),
    UNIQUE (soggetto_nis_id, versione)
);
 
CREATE INDEX idx_soggettonisstorico_soggetto ON SoggettoNISStorico (soggetto_nis_id);
CREATE INDEX idx_soggettonisstorico_validita ON SoggettoNISStorico (soggetto_nis_id, valido_da, valido_a);
 
 

CREATE TABLE ImpresaCollegata (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soggetto_nis_id         NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    ragione_sociale         VARCHAR2(255) NOT NULL,
    codice_fiscale          VARCHAR2(16) NOT NULL,
    parametro_collegamento  VARCHAR2(255)
);
 
CREATE INDEX idx_impresacollegata_soggetto ON ImpresaCollegata (soggetto_nis_id);
 
 

CREATE TABLE PuntoDiContatto (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soggetto_nis_id     NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    nome                VARCHAR2(255) NOT NULL,
    ruolo               VARCHAR2(30) NOT NULL
                        CHECK (ruolo IN ('CONTATTO', 'SOSTITUTO', 'REFERENTE_CSIRT', 'SEGRETERIA')),
    email               VARCHAR2(255),
    telefono            VARCHAR2(30),
    delega              VARCHAR2(255)             -- riferimento/estremi della delega del rappresentante legale
);
 
CREATE INDEX idx_puntodicontatto_soggetto ON PuntoDiContatto (soggetto_nis_id);
 
 
CREATE TABLE OrganoAmministrazione (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soggetto_nis_id     NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    nome                VARCHAR2(255) NOT NULL,
    ruolo               VARCHAR2(100) NOT NULL    -- es. "Amministratore Delegato", "Consigliere"
);
 
CREATE INDEX idx_organoamministrazione_soggetto ON OrganoAmministrazione (soggetto_nis_id);
 
 
CREATE TABLE DominioInternet (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soggetto_nis_id     NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    nome_dominio        VARCHAR2(255) NOT NULL
);
 
CREATE INDEX idx_dominiointernet_soggetto ON DominioInternet (soggetto_nis_id);
 
CREATE TABLE IndirizzoIPPubblico (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soggetto_nis_id     NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    indirizzo           VARCHAR2(45) NOT NULL             -- tipo nativo PostgreSQL per IP
);
 
CREATE INDEX idx_indirizzoippubblico_soggetto ON IndirizzoIPPubblico (soggetto_nis_id);
 

CREATE TABLE AccordoCondivisioneInformazioni (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soggetto_nis_id         NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    controparte_soggetto_id NUMBER(19) REFERENCES SoggettoNIS(id),   -- nullable: non sempre la controparte è un soggetto NIS censito
    controparte             VARCHAR2(255) NOT NULL,               -- testuale, sempre valorizzato come fallback/etichetta
    descrizione             VARCHAR2(500),
    data_stipula            DATE,
    stato                   VARCHAR2(10) DEFAULT 'ATTIVO' NOT NULL
                            CHECK (stato IN ('ATTIVO', 'CESSATO'))
);
 
CREATE INDEX idx_accordocondivisione_soggetto ON AccordoCondivisioneInformazioni (soggetto_nis_id);
 
CREATE TABLE AccordoCondivisioneInformazioniStorico (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accordo_id          NUMBER(19) NOT NULL REFERENCES AccordoCondivisioneInformazioni(id),
    versione            NUMBER(10) NOT NULL,
    controparte         VARCHAR2(255) NOT NULL,
    descrizione         VARCHAR2(500),
    stato               VARCHAR2(10) NOT NULL,
    valido_da           TIMESTAMP NOT NULL,
    valido_a            TIMESTAMP,
    log_estrazione_id   NUMBER(19) NOT NULL REFERENCES LogEstrazione(id),
    UNIQUE (accordo_id, versione)
);
 
CREATE INDEX idx_accordostorico_accordo ON AccordoCondivisioneInformazioniStorico (accordo_id);

 
-- ---------------------------------------------------------------------
-- Sequenza condivisa: garantisce id univoci tra Asset e Servizio,
-- necessaria per la chiave primaria condivisa (class-table inheritance).
-- ---------------------------------------------------------------------
CREATE SEQUENCE seq_elemento_critico;
 

CREATE TABLE ElementoCritico (
    id                  NUMBER(19) DEFAULT seq_elemento_critico.NEXTVAL PRIMARY KEY,
    tipo                VARCHAR2(10) NOT NULL CHECK (tipo IN ('ASSET', 'SERVIZIO')),
    nome                VARCHAR2(255) NOT NULL,
    soggetto_nis_id     NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    stato               VARCHAR2(10) DEFAULT 'ATTIVO' NOT NULL
                        CHECK (stato IN ('ATTIVO', 'DISMESSO')),
    data_inizio_validita TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    data_fine_validita  TIMESTAMP              -- NULL se attivo
);
 
CREATE INDEX idx_elementocritico_soggetto ON ElementoCritico (soggetto_nis_id);
CREATE INDEX idx_elementocritico_tipo ON ElementoCritico (tipo);
 

CREATE TABLE ElementoCriticoStorico (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    elemento_critico_id NUMBER(19) NOT NULL REFERENCES ElementoCritico(id),
    versione            NUMBER(10) NOT NULL,
    nome                VARCHAR2(255) NOT NULL,
    soggetto_nis_id     NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    stato               VARCHAR2(10) NOT NULL,
    valido_da           TIMESTAMP NOT NULL,
    valido_a            TIMESTAMP,
    log_estrazione_id   NUMBER(19) NOT NULL REFERENCES LogEstrazione(id),
    UNIQUE (elemento_critico_id, versione)
);
 
CREATE INDEX idx_elementocriticostorico_elemento ON ElementoCriticoStorico (elemento_critico_id);
CREATE INDEX idx_elementocriticostorico_validita ON ElementoCriticoStorico (elemento_critico_id, valido_da, valido_a);
 
 
CREATE TABLE Asset (
    id          NUMBER(19) PRIMARY KEY REFERENCES ElementoCritico(id),
    tipo_asset  VARCHAR2(20) NOT NULL
                CHECK (tipo_asset IN ('HARDWARE', 'SOFTWARE', 'FLUSSO_RETE', 'SERVIZIO_FORNITORE')),
    rilevante   NUMBER(1) DEFAULT 0 NOT NULL
                CHECK (rilevante IN (0,1))  -- "sistemi informativi e di rete rilevanti", GV.OC-4
);
 
 
-- ---------------------------------------------------------------------
-- Servizio — sottoclasse (categorizzazione art. 20-21 piattaforma ACN)
-- ---------------------------------------------------------------------
CREATE TABLE Servizio (
    id                  NUMBER(19) PRIMARY KEY REFERENCES ElementoCritico(id),
    descrizione         VARCHAR2(500),
    categoria_rilevanza VARCHAR2(50)              -- nullable: modello ACN non ancora definitivo alla data di raccolta fonti
);
 
 
CREATE TABLE ServizioStatoMembro (
    servizio_id     NUMBER(19) NOT NULL REFERENCES Servizio(id),
    stato_membro    CHAR(2) NOT NULL,           -- codice ISO 3166-1 alpha-2
    PRIMARY KEY (servizio_id, stato_membro)
);
 

CREATE TABLE AssetServizio (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id    NUMBER(19) NOT NULL REFERENCES Asset(id),
    servizio_id NUMBER(19) NOT NULL REFERENCES Servizio(id),
    stato       VARCHAR2(10) DEFAULT 'ATTIVA' NOT NULL
                CHECK (stato IN ('ATTIVA', 'CESSATA')),
    UNIQUE (asset_id, servizio_id)               -- una sola relazione "corrente" per coppia
);
 
CREATE INDEX idx_assetservizio_asset ON AssetServizio (asset_id);
CREATE INDEX idx_assetservizio_servizio ON AssetServizio (servizio_id);
 
CREATE TABLE AssetServizioStorico (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_servizio_id   NUMBER(19) NOT NULL REFERENCES AssetServizio(id),
    versione            NUMBER(10) NOT NULL,
    stato               VARCHAR2(10) NOT NULL,
    valido_da           TIMESTAMP NOT NULL,
    valido_a            TIMESTAMP,
    log_estrazione_id   NUMBER(19) NOT NULL REFERENCES LogEstrazione(id),
    UNIQUE (asset_servizio_id, versione)
);
 
CREATE INDEX idx_assetserviziostorico_rel ON AssetServizioStorico (asset_servizio_id);


CREATE TABLE Fornitore (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    denominazione       VARCHAR2(255) NOT NULL,
    codice_fiscale      VARCHAR2(16) NOT NULL UNIQUE,
    paese_sede_legale   CHAR(2) NOT NULL           -- codice ISO 3166-1 alpha-2
);
 
CREATE TABLE FornitoreStorico (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornitore_id        NUMBER(19) NOT NULL REFERENCES Fornitore(id),
    versione            NUMBER(10) NOT NULL,
    denominazione       VARCHAR2(255) NOT NULL,
    paese_sede_legale   CHAR(2) NOT NULL,
    valido_da           TIMESTAMP NOT NULL,
    valido_a            TIMESTAMP,
    log_estrazione_id   NUMBER(19) NOT NULL REFERENCES LogEstrazione(id),
    UNIQUE (fornitore_id, versione)
);
 
CREATE INDEX idx_fornitorestorico_fornitore ON FornitoreStorico (fornitore_id);
 

CREATE TABLE CodiceCPV (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice      VARCHAR2(10) NOT NULL UNIQUE,
    descrizione VARCHAR2(255) NOT NULL
);
 
CREATE TABLE FornitoreCPV (
    fornitore_id    NUMBER(19) NOT NULL REFERENCES Fornitore(id),
    cpv_id          NUMBER(19) NOT NULL REFERENCES CodiceCPV(id),
    PRIMARY KEY (fornitore_id, cpv_id)
);
 

CREATE TABLE Dipendenza (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornitore_id            NUMBER(19) NOT NULL REFERENCES Fornitore(id),
    elemento_critico_id     NUMBER(19) NOT NULL REFERENCES ElementoCritico(id),
    criterio_rilevanza      VARCHAR2(20) NOT NULL
                            CHECK (criterio_rilevanza IN ('ICT', 'NON_FUNGIBILE')),
    tipologia_fornitura     VARCHAR2(255),
    referente_contatto      VARCHAR2(255),
    stato                   VARCHAR2(10) DEFAULT 'ATTIVA' NOT NULL
                            CHECK (stato IN ('ATTIVA', 'CESSATA')),
    UNIQUE (fornitore_id, elemento_critico_id)
);
 
CREATE INDEX idx_dipendenza_fornitore ON Dipendenza (fornitore_id);
CREATE INDEX idx_dipendenza_elemento ON Dipendenza (elemento_critico_id);
 
CREATE TABLE DipendenzaStorico (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dipendenza_id       NUMBER(19) NOT NULL REFERENCES Dipendenza(id),
    versione            NUMBER(10) NOT NULL,
    criterio_rilevanza  VARCHAR2(20) NOT NULL,
    tipologia_fornitura VARCHAR2(255),
    referente_contatto  VARCHAR2(255),
    stato               VARCHAR2(10) NOT NULL,
    valido_da           TIMESTAMP NOT NULL,
    valido_a            TIMESTAMP,
    log_estrazione_id   NUMBER(19) NOT NULL REFERENCES LogEstrazione(id),
    UNIQUE (dipendenza_id, versione)
);
 
CREATE INDEX idx_dipendenzastorico_dipendenza ON DipendenzaStorico (dipendenza_id);
  

CREATE TABLE TipoIncidente (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice                  VARCHAR2(10) NOT NULL,     -- 'IS-1'..'IS-4'
    descrizione             VARCHAR2(500) NOT NULL,
    versione_determinazione VARCHAR2(50) DEFAULT '164179/2025' NOT NULL,
    data_inizio_validita    DATE DEFAULT DATE '2025-04-30' NOT NULL,
    data_fine_validita      DATE,                     -- NULL se in vigore
    UNIQUE (codice, versione_determinazione)
);


CREATE TABLE IncidenteApplicabilita (
    tipo_incidente_id   NUMBER(19) NOT NULL REFERENCES TipoIncidente(id),
    tipo_soggetto_id    NUMBER(5) NOT NULL REFERENCES TipoSoggettoNIS(id),
    PRIMARY KEY (tipo_incidente_id, tipo_soggetto_id)
);
 

CREATE TABLE CategoriaIncidente (
    id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome    VARCHAR2(50) NOT NULL UNIQUE
);
 

CREATE TABLE Incidente (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_incidente_id   NUMBER(19) NOT NULL REFERENCES TipoIncidente(id),
    soggetto_nis_id     NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    categoria_id        NUMBER(19) REFERENCES CategoriaIncidente(id),   -- nullable: non sempre nota da subito
    data_evidenza       TIMESTAMP NOT NULL,       -- da qui decorrono i termini 24h/72h
    gravita             VARCHAR2(20)
                        CHECK (gravita IN ('BASSA', 'MEDIA', 'ALTA', 'CRITICA')),
    root_cause          VARCHAR2(500)              -- testo libero: causa originaria, spesso nota solo a posteriori
);
 
CREATE INDEX idx_incidente_soggetto ON Incidente (soggetto_nis_id);
CREATE INDEX idx_incidente_data ON Incidente (data_evidenza);
 
 
CREATE TABLE IncidenteElementoCritico (
    incidente_id        NUMBER(19) NOT NULL REFERENCES Incidente(id),
    elemento_critico_id NUMBER(19) NOT NULL REFERENCES ElementoCritico(id),
    PRIMARY KEY (incidente_id, elemento_critico_id)
);
 

CREATE TABLE NotificaIncidente (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incidente_id        NUMBER(19) NOT NULL REFERENCES Incidente(id),
    tipo                VARCHAR2(25) NOT NULL
                        CHECK (tipo IN ('PRE_NOTIFICA', 'NOTIFICA', 'RELAZIONE_INTERMEDIA',
                                         'RELAZIONE_FINALE', 'RELAZIONE_MENSILE')),
    data_trasmissione   TIMESTAMP NOT NULL,
    contenuto           CLOB
);
 
CREATE INDEX idx_notificaincidente_incidente ON NotificaIncidente (incidente_id);
 

CREATE TABLE IndicatoreCompromissione (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incidente_id        NUMBER(19) NOT NULL REFERENCES Incidente(id),
    tipo                VARCHAR2(20) NOT NULL
                        CHECK (tipo IN ('IP', 'HASH', 'DOMINIO', 'URL', 'EMAIL')),
    valore              VARCHAR2(500) NOT NULL,
    data_rilevazione    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
 
CREATE INDEX idx_ioc_incidente ON IndicatoreCompromissione (incidente_id);
 
 
CREATE TABLE TimelineEvento (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incidente_id        NUMBER(19) NOT NULL REFERENCES Incidente(id),
    data_ora            TIMESTAMP NOT NULL,
    descrizione         VARCHAR2(500) NOT NULL,
    fase                VARCHAR2(20) NOT NULL
                        CHECK (fase IN ('RILEVAMENTO', 'INVESTIGAZIONE', 'CONTENIMENTO',
                                         'ERADICAZIONE', 'RIPRISTINO'))
);
 
CREATE INDEX idx_timeline_incidente ON TimelineEvento (incidente_id, data_ora);
 

CREATE TABLE AttivitaRisposta (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incidente_id            NUMBER(19) NOT NULL REFERENCES Incidente(id),
    fase                    VARCHAR2(20) NOT NULL
                            CHECK (fase IN ('CONTENIMENTO', 'ERADICAZIONE')),
    descrizione             VARCHAR2(500) NOT NULL,
    motivazione             VARCHAR2(500),
    struttura_coinvolta_id  NUMBER(19),                 -- FK aggiunta nel Blocco 6
    esito                   VARCHAR2(255),
    data_esecuzione         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
 
CREATE INDEX idx_attivitarisposta_incidente ON AttivitaRisposta (incidente_id);


CREATE TABLE PersonaleGovernance (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR2(255) NOT NULL,
    ruolo               VARCHAR2(100) NOT NULL,     -- es. "Amministratore di sistema", "Membro organizzazione sicurezza"
    soggetto_nis_id     NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    punto_contatto_id   NUMBER(19) REFERENCES PuntoDiContatto(id)
);
 
CREATE INDEX idx_personalegovernance_soggetto ON PersonaleGovernance (soggetto_nis_id);
 

CREATE TABLE TipoDocumentoGovernance (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice              VARCHAR2(20) NOT NULL UNIQUE,   -- es. 'GV.PO-01', 'RS.MA-01'
    nome                VARCHAR2(255) NOT NULL,
    ambito_politica     VARCHAR2(10)                    -- 'a'..'p', nullable
);


CREATE TABLE DocumentoGovernanceApplicabilita (
    tipo_documento_id   NUMBER(19) NOT NULL REFERENCES TipoDocumentoGovernance(id),
    tipo_soggetto_id    NUMBER(5) NOT NULL REFERENCES TipoSoggettoNIS(id),
    PRIMARY KEY (tipo_documento_id, tipo_soggetto_id)
);
 

CREATE TABLE DocumentoGovernance (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soggetto_nis_id         NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    tipo_documento_id       NUMBER(19) NOT NULL REFERENCES TipoDocumentoGovernance(id),
    data_approvazione       DATE,
    approvato_da            NUMBER(19) REFERENCES OrganoAmministrazione(id),
    data_ultimo_riesame     DATE,
    versione                VARCHAR2(20)
);
 
CREATE INDEX idx_documentogovernance_soggetto ON DocumentoGovernance (soggetto_nis_id);
 
CREATE TABLE DocumentoGovernanceStorico (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id        NUMBER(19) NOT NULL REFERENCES DocumentoGovernance(id),
    versione            NUMBER(10) NOT NULL,
    data_approvazione   DATE,
    approvato_da        NUMBER(19),
    data_ultimo_riesame DATE,
    valido_da           TIMESTAMP NOT NULL,
    valido_a            TIMESTAMP,
    log_estrazione_id   NUMBER(19) NOT NULL REFERENCES LogEstrazione(id),
    UNIQUE (documento_id, versione)
);
 
CREATE INDEX idx_documentogovernancestorico_doc ON DocumentoGovernanceStorico (documento_id);
 

CREATE TABLE DocumentoGovernanceElementoCritico (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id            NUMBER(19) NOT NULL REFERENCES DocumentoGovernance(id),
    elemento_critico_id     NUMBER(19) NOT NULL REFERENCES ElementoCritico(id),
    stato                   VARCHAR2(10) DEFAULT 'ATTIVA' NOT NULL
                            CHECK (stato IN ('ATTIVA', 'CESSATA')),
    UNIQUE (documento_id, elemento_critico_id)
);
 
CREATE INDEX idx_dgec_documento ON DocumentoGovernanceElementoCritico (documento_id);
CREATE INDEX idx_dgec_elemento ON DocumentoGovernanceElementoCritico (elemento_critico_id);
 
CREATE TABLE DocumentoGovernanceElementoCriticoStorico (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_elemento_id   NUMBER(19) NOT NULL REFERENCES DocumentoGovernanceElementoCritico(id),
    versione                NUMBER(10) NOT NULL,
    stato                   VARCHAR2(10) NOT NULL,
    valido_da               TIMESTAMP NOT NULL,
    valido_a                TIMESTAMP,
    log_estrazione_id       NUMBER(19) NOT NULL REFERENCES LogEstrazione(id),
    UNIQUE (documento_elemento_id, versione)
);
 

CREATE TABLE MisuraSicurezza (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice      VARCHAR2(20) NOT NULL UNIQUE,   -- es. 'GV.SC-04'
    categoria   VARCHAR2(100) NOT NULL,          -- es. "Gestione del rischio della catena di approvvigionamento"
    descrizione VARCHAR2(500) NOT NULL
);
 

CREATE TABLE RequisitoMisura (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice                  VARCHAR2(30) NOT NULL,      -- es. 'GV.SC-04.1' -- stabile nel tempo
    misura_id               NUMBER(19) NOT NULL REFERENCES MisuraSicurezza(id),
    numero_punto            NUMBER(10) NOT NULL,
    testo                   VARCHAR2(1000) NOT NULL,
    versione_determinazione VARCHAR2(50) DEFAULT '164179/2025' NOT NULL,
    data_inizio_validita    DATE DEFAULT DATE '2025-04-30' NOT NULL,
    data_fine_validita      DATE,                      -- NULL se in vigore
    UNIQUE (codice, versione_determinazione)
);
 
CREATE INDEX idx_requisitomisura_misura ON RequisitoMisura (misura_id);
 

CREATE TABLE MisuraApplicabilita (
    requisito_id        NUMBER(19) NOT NULL REFERENCES RequisitoMisura(id),
    tipo_soggetto_id    NUMBER(5) NOT NULL REFERENCES TipoSoggettoNIS(id),
    PRIMARY KEY (requisito_id, tipo_soggetto_id)
);
 

CREATE TABLE StatoAdempimentoRequisito (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisito_id            NUMBER(19) NOT NULL REFERENCES RequisitoMisura(id),
    soggetto_nis_id         NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    stato                   VARCHAR2(25) NOT NULL
                            CHECK (stato IN ('NON_ATTUATO', 'PARZIALMENTE_ATTUATO', 'ATTUATO', 'NON_APPLICABILE')),
    data_valutazione        DATE DEFAULT CURRENT_DATE NOT NULL,
    responsabile_id         NUMBER(19) REFERENCES PersonaleGovernance(id),
    documento_evidenza_id   NUMBER(19) REFERENCES DocumentoGovernance(id),   -- FK diretta, nullable
    note                    VARCHAR2(1000),
    UNIQUE (requisito_id, soggetto_nis_id)   -- una sola attestazione corrente per coppia
);
 
CREATE INDEX idx_statoadempimento_soggetto ON StatoAdempimentoRequisito (soggetto_nis_id);
CREATE INDEX idx_statoadempimento_requisito ON StatoAdempimentoRequisito (requisito_id);
 
CREATE TABLE StatoAdempimentoRequisitoStorico (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stato_adempimento_id    NUMBER(19) NOT NULL REFERENCES StatoAdempimentoRequisito(id),
    versione                NUMBER(10) NOT NULL,
    stato                   VARCHAR2(25) NOT NULL,
    data_valutazione        DATE NOT NULL,
    responsabile_id         NUMBER(19),
    documento_evidenza_id   NUMBER(19),
    note                    VARCHAR2(1000),
    valido_da               TIMESTAMP NOT NULL,
    valido_a                TIMESTAMP,
    log_estrazione_id       NUMBER(19) NOT NULL REFERENCES LogEstrazione(id),
    UNIQUE (stato_adempimento_id, versione)
);
 
CREATE INDEX idx_statoadempimentostorico_stato ON StatoAdempimentoRequisitoStorico (stato_adempimento_id);
 

ALTER TABLE AttivitaRisposta
    ADD CONSTRAINT fk_attivitarisposta_struttura
    FOREIGN KEY (struttura_coinvolta_id) REFERENCES PersonaleGovernance(id);


CREATE TABLE InvioACN (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soggetto_nis_id     NUMBER(19) NOT NULL REFERENCES SoggettoNIS(id),
    tipo_invio          VARCHAR2(25) NOT NULL
                        CHECK (tipo_invio IN ('REGISTRAZIONE', 'AGGIORNAMENTO_ANNUALE',
                                               'AGGIORNAMENTO_CONTINUO', 'CATEGORIZZAZIONE')),
    data_invio          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    periodo_riferimento NUMBER(10) NOT NULL            -- anno di riferimento
);
 
CREATE INDEX idx_invioacn_soggetto ON InvioACN (soggetto_nis_id);
CREATE INDEX idx_invioacn_data ON InvioACN (data_invio);